name: Ejecutar pruebas de aceptación

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Instalar dependencias del frontend
        run: npm install --prefix Ahorcado/ahorcado-front

      - name: Construir el frontend
        run: npm run build --prefix Ahorcado/ahorcado-front

      - name: Instalar dependencias del backend y cypress
        run: npm install --prefix Ahorcado

      - name: Ejecutar el backend
        run: npm start --prefix Ahorcado &

      - name: Ejecutar el frontend
        run: npm start --prefix Ahorcado/ahorcado-front &

      - name: Esperar a que el backend esté listo
        run: sleep 10

      - name: Ejecutar pruebas de Cypress
        run: npx cypress run --prefix Ahorcado
